# Generated by Django 2.2 on 2020-01-20 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.CharField(max_length=400, primary_key=True, serialize=False)),
                ('account_id', models.CharField(max_length=400)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=200)),
                ('iso_currency_code', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=10, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=10, max_digits=100, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=10, max_digits=100, null=True)),
                ('store_number', models.TextField(blank=True, null=True)),
                ('payment_channel', models.CharField(max_length=400)),
                ('categories', models.ManyToManyField(to='coreapp.TransactionCategory')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coreapp.PlaidItem')),
                ('store_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coreapp.StoreName')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.AddField(
            model_name='storename',
            name='categories',
            field=models.ManyToManyField(to='coreapp.TransactionCategory'),
        ),
    ]
